server:
  port: 8030
eureka:
  instance:
    prefer-ip-address: true  #显示主机id
  client:
    service-url:
      defaultZone:
        http://localhost:8761/eureka/
spring:
  application:
    name: user-service   #指定应用名称
  datasource:
    url: jdbc:mysql://localhost:3306/lala?serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver