server:
  port: 8050
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone:
        http://localhost:8761/eureka/
spring:
  application:
    name: gateway-zuul
zuul:
  routes:
    news-serviceId:
      path: /news/**
      service-id: news-service